# zshrc
# source all the zsh files
# startups.zsh
# ZSH_THEME="powerlevel9k/powerlevel9k"
ZSH_THEME="honukai"
plugins=(
    zsh-autosuggestions
    git
    zsh-syntax-highlighting
    zsh-completions
)

# export PATH="/usr/local/opt/node@12/bin:$PATH"
alias tmux='TERM=xterm-256color tmux'
if which tmux 2>&1 >/dev/null && [ "${USER}" != "root" ]; then
    # if no session is started, attach to the last exitted session or start a new session
    test -z ${TMUX} && ( ( tmux ls | grep -v '(attached)$' && tmux attach ) || tmux )

    # when quitting tmux, try to attach to any unattached sessions
    while test -z ${TMUX}; do
        ( tmux ls | grep -v '(attached)$' && tmux attach ) || break
    done
fi

export ZSH=$HOME/.oh-my-zsh
export EDITOR="nano"
source $ZSH/oh-my-zsh.sh
export LANG="en_US.UTF-8"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;